<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('products')->delete();

        DB::table('products')->insert(array (
            0 =>
                array (
                    'id' => 1,
                    'code' => '8100_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 1,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            1 =>
                array (
                    'id' => 2,
                    'code' => '8200_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 1,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            2 =>
                array (
                    'id' => 3,
                    'code' => '8430S_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 1,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            3 =>
                array (
                    'id' => 4,
                    'code' => '6410_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 2,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            4 =>
                array (
                    'id' => 5,
                    'code' => '6430_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 2,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            5 =>
                array (
                    'id' => 6,
                    'code' => '1660_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            6 =>
                array (
                    'id' => 7,
                    'code' => '2600_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            7 =>
                array (
                    'id' => 8,
                    'code' => '2700_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            8 =>
                array (
                    'id' => 9,
                    'code' => '9999_20',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 2,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            9 =>
                array (
                    'id' => 10,
                    'code' => 'FS9999_20',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 2,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            10 =>
                array (
                    'id' => 11,
                    'code' => 'MAX9000_05',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 1,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            11 =>
                array (
                    'id' => 12,
                    'code' => 'MAX9000_20',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 2,
                    'group_id' => 3,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            12 =>
                array (
                    'id' => 13,
                    'code' => '2420_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 4,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            13 =>
                array (
                    'id' => 14,
                    'code' => '2430S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 4,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            14 =>
                array (
                    'id' => 15,
                    'code' => '2430_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 4,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            15 =>
                array (
                    'id' => 16,
                    'code' => 'G228_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 4,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            16 =>
                array (
                    'id' => 17,
                    'code' => '2200L_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 5,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            17 =>
                array (
                    'id' => 18,
                    'code' => '2200E_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 5,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            18 =>
                array (
                    'id' => 19,
                    'code' => 'G225_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 5,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            19 =>
                array (
                    'id' => 20,
                    'code' => '2000S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            20 =>
                array (
                    'id' => 21,
                    'code' => '2100_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            21 =>
                array (
                    'id' => 22,
                    'code' => 'GT01_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            22 =>
                array (
                    'id' => 23,
                    'code' => '2200_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            23 =>
                array (
                    'id' => 24,
                    'code' => 'GT02_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            24 =>
                array (
                    'id' => 25,
                    'code' => '2200PLUS_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            25 =>
                array (
                    'id' => 26,
                    'code' => 'G221_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            26 =>
                array (
                    'id' => 27,
                    'code' => 'Max01_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            27 =>
                array (
                    'id' => 28,
                    'code' => 'G222_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            28 =>
                array (
                    'id' => 29,
                    'code' => 'Max02_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            29 =>
                array (
                    'id' => 30,
                    'code' => '2000SF_40',
                    'name' => null,
                    'detail' => 'Dạng mảnh không kháng sinh',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            30 =>
                array (
                    'id' => 31,
                    'code' => '2000SF_40',
                    'name' => null,
                    'detail' => 'Dạng viên không kháng sinh',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            31 =>
                array (
                    'id' => 32,
                    'code' => '2000S_40',
                    'name' => null,
                    'detail' => 'Lô 05, dạng viên',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            32 =>
                array (
                    'id' => 33,
                    'code' => '2100F0_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            33 =>
                array (
                    'id' => 34,
                    'code' => '2200F1_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            34 =>
                array (
                    'id' => 35,
                    'code' => '2200F2_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            35 =>
                array (
                    'id' => 36,
                    'code' => '2000SP_40',
                    'name' => null,
                    'detail' => 'Dạng viên',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            36 =>
                array (
                    'id' => 37,
                    'code' => '2000SP_40',
                    'name' => null,
                    'detail' => 'Dạng mảnh',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            37 =>
                array (
                    'id' => 38,
                    'code' => '2000SM_40',
                    'name' => null,
                    'detail' => 'Dạng mảnh không khánh sinh',
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            38 =>
                array (
                    'id' => 39,
                    'code' => '2100S_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            39 =>
                array (
                    'id' => 40,
                    'code' => '2200S_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 6,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            40 =>
                array (
                    'id' => 41,
                    'code' => '1110P_05',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 1,
                    'group_id' => 7,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            41 =>
                array (
                    'id' => 42,
                    'code' => '1110P_20',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 2,
                    'group_id' => 7,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            42 =>
                array (
                    'id' => 43,
                    'code' => '1120_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 7,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            43 =>
                array (
                    'id' => 44,
                    'code' => 'T1120_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 7,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            44 =>
                array (
                    'id' => 45,
                    'code' => 'H120_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 7,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            45 =>
                array (
                    'id' => 46,
                    'code' => '1110P_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 7,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            46 =>
                array (
                    'id' => 47,
                    'code' => '1120_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 7,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            47 =>
                array (
                    'id' => 48,
                    'code' => '1100FS_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 8,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            48 =>
                array (
                    'id' => 49,
                    'code' => 'H125FS_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 8,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            49 =>
                array (
                    'id' => 50,
                    'code' => '1200L_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 9,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            50 =>
                array (
                    'id' => 51,
                    'code' => '1100S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            51 =>
                array (
                    'id' => 52,
                    'code' => 'T1100S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            52 =>
                array (
                    'id' => 53,
                    'code' => '1100_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            53 =>
                array (
                    'id' => 54,
                    'code' => '1130S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            54 =>
                array (
                    'id' => 55,
                    'code' => 'T1130S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            55 =>
                array (
                    'id' => 56,
                    'code' => '1135S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            56 =>
                array (
                    'id' => 57,
                    'code' => '1200S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            57 =>
                array (
                    'id' => 58,
                    'code' => '1410_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            58 =>
                array (
                    'id' => 59,
                    'code' => 'T1410_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            59 =>
                array (
                    'id' => 60,
                    'code' => '1410E_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            60 =>
                array (
                    'id' => 61,
                    'code' => '1430_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            61 =>
                array (
                    'id' => 62,
                    'code' => 'T1430_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            62 =>
                array (
                    'id' => 63,
                    'code' => 'H121S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            63 =>
                array (
                    'id' => 64,
                    'code' => 'H122S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            64 =>
                array (
                    'id' => 65,
                    'code' => 'H128_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            65 =>
                array (
                    'id' => 66,
                    'code' => 'H129_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            66 =>
                array (
                    'id' => 67,
                    'code' => '1680R_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            67 =>
                array (
                    'id' => 68,
                    'code' => 'MAX101S_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            68 =>
                array (
                    'id' => 69,
                    'code' => '1100S_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 10,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            69 =>
                array (
                    'id' => 70,
                    'code' => '1130S_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 10,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            70 =>
                array (
                    'id' => 71,
                    'code' => '1410_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 10,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            71 =>
                array (
                    'id' => 72,
                    'code' => '1430_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 10,
                    'category_id' => 1,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            72 =>
                array (
                    'id' => 73,
                    'code' => '4410_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 11,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            73 =>
                array (
                    'id' => 74,
                    'code' => '4420_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 11,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            74 =>
                array (
                    'id' => 75,
                    'code' => 'V428_40',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 4,
                    'group_id' => 11,
                    'category_id' =>3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            75 =>
                array (
                    'id' => 76,
                    'code' => '4100_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 12,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            76 =>
                array (
                    'id' => 77,
                    'code' => '4200_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 12,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            77 =>
                array (
                    'id' => 78,
                    'code' => '4200E_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 12,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            78 =>
                array (
                    'id' => 79,
                    'code' => 'V421_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 12,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            79 =>
                array (
                    'id' => 80,
                    'code' => 'V422_25',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 12,
                    'category_id' => 3,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            80 =>
                array (
                    'id' => 81,
                    'code' => '2000S_25',
                    'name' => null,
                    'detail' => 'Lô 02, dạng mảnh không cầu trùng',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            81 =>
                array (
                    'id' => 82,
                    'code' => '2000S_25',
                    'name' => null,
                    'detail' => 'Lô 05, dạng viên không kháng sinh',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            82 =>
                array (
                    'id' => 83,
                    'code' => '2000S_25',
                    'name' => null,
                    'detail' => 'Lô 06, dạng viên có kháng sinh',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            83 =>
                array (
                    'id' => 84,
                    'code' => '8200_25',
                    'name' => null,
                    'detail' => 'Lô 02',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 1,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            84 =>
                array (
                    'id' => 85,
                    'code' => '2200_25',
                    'name' => null,
                    'detail' => 'Lô 02',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            85 =>
                array (
                    'id' => 86,
                    'code' => '2200PLUS_25',
                    'name' => null,
                    'detail' => 'Lô 06',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            86 =>
                array (
                    'id' => 87,
                    'code' => 'G2222_25',
                    'name' => null,
                    'detail' => 'Lô 02',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 6,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            87 =>
                array (
                    'id' => 88,
                    'code' => '1130S_25',
                    'name' => null,
                    'detail' => 'Lô 02',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            88 =>
                array (
                    'id' => 89,
                    'code' => 'T1130S_25',
                    'name' => null,
                    'detail' => 'Lô 02',
                    'description' => null,
                    'package_id' => 3,
                    'group_id' => 10,
                    'category_id' => 2,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            89 =>
                array (
                    'id' => 90,
                    'code' => '1110P',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 7,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            90 =>
                array (
                    'id' => 91,
                    'code' => 'T1120',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 7,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            91 =>
                array (
                    'id' => 92,
                    'code' => 'T1100S',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 10,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            92 =>
                array (
                    'id' => 93,
                    'code' => 'T1130S',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 10,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            93 =>
                array (
                    'id' => 94,
                    'code' => 'T1410',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 10,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
            94 =>
                array (
                    'id' => 95,
                    'code' => 'T1430',
                    'name' => null,
                    'detail' => null,
                    'description' => null,
                    'package_id' => 5,
                    'group_id' => 10,
                    'category_id' => 4,
                    'created_at' => Carbon::now(),
                    'updated_at' => Carbon::now(),
                ),
        ));
    }
}
